---
- hosts: all
  vars:
    mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
    mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
    mssql_accept_microsoft_sql_server_standard_eula: true
    mssql_password: "123@Redhat"
    mssql_edition: Evaluation
    mssql_version: 2022  # Added this line to specify the SQL Server version
    mssql_ip_address: 0.0.0.0
    mssql_enable_sql_agent: true
    mssql_install_fts: true
    mssql_install_powershell: true
    mssql_tune_for_fua_storage: true
    firewall:
      port: ['1433/tcp']
      state: enabled

  roles:
    - microsoft.sql.server
    - redhat.rhel_system_roles.firewall